require('nvim-treesitter.configs').setup({
  auto_install = true,
  ensure_installed = {
    'bash',
    'c',
    'cmake',
    'cpp',
    'fish',
    'java',
    'javascript',
    'jsdoc',
    'json',
    'lua',
    'make',
    'markdown',
    'markdown_inline',
    'python',
    'regex',
    'rust',
    'toml',
    'typescript',
    'vim',
    'yaml',
    'zig',
  },
  highlight = { enable = true },
})
