require('plugins.config.mini.align')
require('plugins.config.mini.comment')
require('plugins.config.mini.completion')
require('plugins.config.mini.statusline')

require('mini.indentscope').setup({})
require('mini.jump').setup({})
require('mini.jump2d').setup({})
require('mini.pairs').setup({})
require('mini.surround').setup({})
require('mini.tabline').setup({})
